/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.MenuPrincipal.onglets;

import ca.ulaval.glo2004.afficheur.MenuPrincipal.objetsUI.ObjetScenarioCarte;

/**
 *
 * @author Jonathan
 */
public class OngletCreationScenarioCarte extends OngletUI {

    public int getIndexCourant() {
        int index = -1;
        if(getCourant() != null) {
            ObjetScenarioCarte osc = (ObjetScenarioCarte) getCourant();
            index = osc.getIndex();
        }
        return index;
    }

    public void ajouterObjetUI(ObjetScenarioCarte osc) {
        objets.add(osc);
        
        if (objets.size() == 1) {
            this.onClickObjetUI(osc);
        }
    }
    
    public void clear() {
        objets.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(46, 52, 64));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 35, 35));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
