/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.objetsUI;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.afficheur.onglets.OngletCarte;
import javax.swing.ImageIcon;


public class ObjetCarte extends ObjetUI {    
    public ObjetCarte(OngletCarte tab) {
        super(tab);
        initComponents();
        
        MapName.setFont(FontRegister.RobotoRegular.deriveFont(21.3062f));
    }
    
    public void setMapName(String name) {
        MapName.setText(name);
    }
    
    public String getNomCarte() {
        return MapName.getText();
    }
    
    public void setMapImage(ImageIcon image) {
        MapImage.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MapName = new javax.swing.JLabel();
        MapImage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(19, 0, 19, 0));
        setMaximumSize(new java.awt.Dimension(351, 215));
        setMinimumSize(new java.awt.Dimension(351, 215));
        setPreferredSize(new java.awt.Dimension(351, 215));
        setLayout(new java.awt.BorderLayout());

        MapName.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        MapName.setText("Nom de la carte");
        MapName.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 42, 0, 0));
        add(MapName, java.awt.BorderLayout.NORTH);

        MapImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MapImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carte_exemple.png"))); // NOI18N
        add(MapImage, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MapImage;
    private javax.swing.JLabel MapName;
    // End of variables declaration//GEN-END:variables
}
