/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.MenuPrincipal.objetsUI;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.afficheur.MenuPrincipal.onglets.OngletMaladie;


public class ObjetMaladie extends ObjetUI {
    
    public ObjetMaladie(OngletMaladie tab) {
        super(tab);
        initComponents();
        
        NomMaladie.setFont(FontRegister.RobotoRegular.deriveFont(21.3062f));
        setInfectedProgressBar(0.0d);
        setCuredProgressBar(0.0d);
        setDeadProgressBar(0.0d);
    }
    
    public void setNom(String nom) {
        NomMaladie.setText(nom);
    }
    
    public String getNom() {
        return NomMaladie.getText();
    }
    
    public void setInfectedProgressBar(double value) {
        InfectionsBars.setValue(Math.round((float) value));
    }
    
    public void setCuredProgressBar(double value) {
        SainsBar.setValue(Math.round((float) value));
    }
    
    public void setDeadProgressBar(double value) {
        MortsBar.setValue(Math.round((float) value));
    }
    
    public double getInfectionRate() {
        return InfectionsBars.getValue();
    }
    
    public double getCuredRate() {
        return SainsBar.getValue();
    }
    
    public double getDeadRate() {
        return MortsBar.getValue();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomMaladie = new javax.swing.JLabel();
        DiagramPanel = new javax.swing.JPanel();
        Bars = new javax.swing.JPanel();
        InfectionsBars = new javax.swing.JProgressBar();
        SainsBar = new javax.swing.JProgressBar();
        MortsBar = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(351, 215));
        setMinimumSize(new java.awt.Dimension(351, 215));
        setPreferredSize(new java.awt.Dimension(351, 215));

        NomMaladie.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        NomMaladie.setText("Nom de la maladie");
        NomMaladie.setBorder(javax.swing.BorderFactory.createEmptyBorder(19, 42, 0, 0));

        DiagramPanel.setBackground(new java.awt.Color(59, 66, 82));
        DiagramPanel.setMaximumSize(new java.awt.Dimension(349, 85));
        DiagramPanel.setMinimumSize(new java.awt.Dimension(349, 85));
        DiagramPanel.setLayout(new java.awt.BorderLayout());

        Bars.setBackground(new java.awt.Color(59, 66, 82));
        Bars.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 42, 10, 42));
        Bars.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        InfectionsBars.setForeground(new java.awt.Color(191, 97, 106));
        InfectionsBars.setToolTipText("Taux d'infection");
        InfectionsBars.setValue(25);
        InfectionsBars.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        InfectionsBars.setBorderPainted(false);
        Bars.add(InfectionsBars);

        SainsBar.setForeground(new java.awt.Color(163, 190, 140));
        SainsBar.setToolTipText("Taux de guérison");
        SainsBar.setValue(100);
        SainsBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        SainsBar.setBorderPainted(false);
        Bars.add(SainsBar);

        MortsBar.setForeground(new java.awt.Color(180, 142, 173));
        MortsBar.setToolTipText("Taux de mortalité");
        MortsBar.setValue(50);
        MortsBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        MortsBar.setBorderPainted(false);
        Bars.add(MortsBar);

        DiagramPanel.add(Bars, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NomMaladie, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(DiagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NomMaladie)
                .addGap(28, 28, 28)
                .addComponent(DiagramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bars;
    private javax.swing.JPanel DiagramPanel;
    private javax.swing.JProgressBar InfectionsBars;
    private javax.swing.JProgressBar MortsBar;
    private javax.swing.JLabel NomMaladie;
    private javax.swing.JProgressBar SainsBar;
    // End of variables declaration//GEN-END:variables
}
