/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.MenuPrincipal.objetsUI;

import ca.ulaval.glo2004.afficheur.MenuPrincipal.objetsUI.ObjetUI;
import ca.ulaval.glo2004.afficheur.MenuPrincipal.onglets.OngletCreationScenarioCarte;
import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;

public class ObjetScenarioCarte extends ObjetUI {    
    private int index;
    
    public ObjetScenarioCarte(OngletCreationScenarioCarte tab, int index, String nom, int valeurPays, int valeurPopulation) {
        super(tab);
        initComponents();
        
        setIndex(index);
        setNom(nom);
        setPaysValue(valeurPays);
        setPopulationValue(valeurPopulation);
        
        NomCarte.setFont(FontRegister.RobotoRegular.deriveFont(21.3062f));
        PaysTotalLabel1.setFont(FontRegister.RobotoLight.deriveFont(12f));
        PaysTotalValue1.setFont(FontRegister.RobotoLight.deriveFont(12f));
        PopulationTotalLabel.setFont(FontRegister.RobotoLight.deriveFont(12f));
        PopulationTotalValue.setFont(FontRegister.RobotoLight.deriveFont(12f));
    }

    public int getIndex() {
        return index;
    }
    
    public void setIndex(int index) {
        this.index = index;
    }
    
    public void setNom(String text) {
        NomCarte.setText(text);
    }
    
    public void setPaysValue(int value) {
        PaysTotalValue1.setText(String.valueOf(value));
    }
    
    public void setPopulationValue(int value) {
        PopulationTotalValue.setText(String.valueOf(value));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomCarte = new javax.swing.JLabel();
        InfoObjetPanel = new javax.swing.JPanel();
        NombrePaysPanel = new javax.swing.JPanel();
        PaysTotalLabel1 = new javax.swing.JLabel();
        PaysTotalValue1 = new javax.swing.JLabel();
        PopPanel = new javax.swing.JPanel();
        PopulationTotalLabel = new javax.swing.JLabel();
        PopulationTotalValue = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(19, 0, 19, 0));
        setMaximumSize(new java.awt.Dimension(224, 150));
        setMinimumSize(new java.awt.Dimension(224, 150));
        setPreferredSize(new java.awt.Dimension(224, 150));
        setLayout(new java.awt.BorderLayout(0, 25));

        NomCarte.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        NomCarte.setText("Nom de la carte");
        NomCarte.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        NomCarte.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(NomCarte, java.awt.BorderLayout.PAGE_START);

        InfoObjetPanel.setEnabled(false);
        InfoObjetPanel.setFocusable(false);
        InfoObjetPanel.setLayout(new java.awt.GridLayout(2, 0));

        NombrePaysPanel.setLayout(new javax.swing.BoxLayout(NombrePaysPanel, javax.swing.BoxLayout.LINE_AXIS));

        PaysTotalLabel1.setText("Nombre de pays");
        PaysTotalLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        PaysTotalLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        PaysTotalLabel1.setMaximumSize(new java.awt.Dimension(150, 20));
        PaysTotalLabel1.setMinimumSize(new java.awt.Dimension(150, 20));
        PaysTotalLabel1.setPreferredSize(new java.awt.Dimension(150, 20));
        NombrePaysPanel.add(PaysTotalLabel1);

        PaysTotalValue1.setText("0");
        PaysTotalValue1.setToolTipText("");
        PaysTotalValue1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PaysTotalValue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PaysTotalValue1.setMaximumSize(new java.awt.Dimension(200, 20));
        PaysTotalValue1.setMinimumSize(new java.awt.Dimension(200, 20));
        PaysTotalValue1.setPreferredSize(new java.awt.Dimension(200, 20));
        NombrePaysPanel.add(PaysTotalValue1);

        InfoObjetPanel.add(NombrePaysPanel);

        PopPanel.setLayout(new javax.swing.BoxLayout(PopPanel, javax.swing.BoxLayout.LINE_AXIS));

        PopulationTotalLabel.setText("Population totale");
        PopulationTotalLabel.setToolTipText("");
        PopulationTotalLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        PopulationTotalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PopulationTotalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        PopulationTotalLabel.setMaximumSize(new java.awt.Dimension(150, 20));
        PopulationTotalLabel.setMinimumSize(new java.awt.Dimension(150, 20));
        PopulationTotalLabel.setPreferredSize(new java.awt.Dimension(150, 20));
        PopPanel.add(PopulationTotalLabel);

        PopulationTotalValue.setText("0");
        PopulationTotalValue.setToolTipText("");
        PopulationTotalValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PopulationTotalValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PopulationTotalValue.setMaximumSize(new java.awt.Dimension(200, 20));
        PopulationTotalValue.setMinimumSize(new java.awt.Dimension(200, 20));
        PopulationTotalValue.setPreferredSize(new java.awt.Dimension(200, 20));
        PopPanel.add(PopulationTotalValue);

        InfoObjetPanel.add(PopPanel);

        add(InfoObjetPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoObjetPanel;
    private javax.swing.JLabel NomCarte;
    private javax.swing.JPanel NombrePaysPanel;
    private javax.swing.JLabel PaysTotalLabel1;
    private javax.swing.JLabel PaysTotalValue1;
    private javax.swing.JPanel PopPanel;
    private javax.swing.JLabel PopulationTotalLabel;
    private javax.swing.JLabel PopulationTotalValue;
    // End of variables declaration//GEN-END:variables
}