/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.panels;

import ca.ulaval.glo2004.afficheur.PanelArrondi;
import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.domaine.Carte;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Jonathan
 */
public class CarteScenarioPanel extends PanelArrondi {

    /**
     * Creates new form ScenarioMapPanel
     */
    public CarteScenarioPanel() {
        initComponents();
        
        setBackground(new Color(216, 222, 233, 38));
        try {
            MapNameLabel.setFont(FontRegister.RobotoThin.deriveFont(21f));
            AideLabel.setFont(FontRegister.RobotoLight.deriveFont(14f));
        }
        catch(Exception e) {
        }
        
        // Pas besoin en mode creation carte
        BoutonExport.setVisible(false);
        
        setPreviewVisibility(false);
    }
    
    public void setPreviewVisibility(boolean toggle) {
        ContentParent.setVisible(toggle);
    }
    
    public void setCarte(Carte carte) {
        cartePreview.setCarte(carte);
    }
    
    private void prendrePhoto() {
        BufferedImage img = new BufferedImage(cartePreview.getWidth(), cartePreview.getHeight(), BufferedImage.TYPE_INT_RGB);
        
        cartePreview.paint(img.getGraphics());
        
        try {
            ImageIO.write(img, "png", new File("saved.png"));
        }
        catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MapPanelHeader = new javax.swing.JPanel();
        MapNameLabel = new javax.swing.JLabel();
        BoutonExport = new javax.swing.JLabel();
        ContentParent = new javax.swing.JPanel();
        AideParent = new javax.swing.JPanel();
        AidePanel = new ca.ulaval.glo2004.afficheur.PanelArrondi();
        AideLabel = new javax.swing.JLabel();
        cartePreview = new ca.ulaval.glo2004.afficheur.CreationCarte.CartePreview();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.BorderLayout());

        MapPanelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        MapPanelHeader.setOpaque(false);
        MapPanelHeader.setLayout(new java.awt.BorderLayout());

        MapNameLabel.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        MapNameLabel.setText("Aperçu");
        MapPanelHeader.add(MapNameLabel, java.awt.BorderLayout.CENTER);

        BoutonExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_unsplash_20px.png"))); // NOI18N
        BoutonExport.setToolTipText("Exporter la carte en format PNG");
        BoutonExport.setMaximumSize(new java.awt.Dimension(25, 25));
        BoutonExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BoutonExportMouseReleased(evt);
            }
        });
        MapPanelHeader.add(BoutonExport, java.awt.BorderLayout.EAST);

        add(MapPanelHeader, java.awt.BorderLayout.NORTH);

        ContentParent.setOpaque(false);
        ContentParent.setLayout(new javax.swing.OverlayLayout(ContentParent));

        AideParent.setOpaque(false);

        AidePanel.setLayout(new java.awt.BorderLayout());

        AideLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AideLabel.setText("Indice: utilisez la souris pour zoomer et déplacer, comme en mode création.");
        AideLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15));
        AidePanel.add(AideLabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout AideParentLayout = new javax.swing.GroupLayout(AideParent);
        AideParent.setLayout(AideParentLayout);
        AideParentLayout.setHorizontalGroup(
            AideParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AideParentLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(AidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        AideParentLayout.setVerticalGroup(
            AideParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AideParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        ContentParent.add(AideParent);

        javax.swing.GroupLayout cartePreviewLayout = new javax.swing.GroupLayout(cartePreview);
        cartePreview.setLayout(cartePreviewLayout);
        cartePreviewLayout.setHorizontalGroup(
            cartePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        cartePreviewLayout.setVerticalGroup(
            cartePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        ContentParent.add(cartePreview);

        add(ContentParent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonExportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoutonExportMouseReleased
        prendrePhoto();
    }//GEN-LAST:event_BoutonExportMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AideLabel;
    private ca.ulaval.glo2004.afficheur.PanelArrondi AidePanel;
    private javax.swing.JPanel AideParent;
    private javax.swing.JLabel BoutonExport;
    private javax.swing.JPanel ContentParent;
    private javax.swing.JLabel MapNameLabel;
    private javax.swing.JPanel MapPanelHeader;
    private ca.ulaval.glo2004.afficheur.CreationCarte.CartePreview cartePreview;
    // End of variables declaration//GEN-END:variables
}
