/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.panels;

import ca.ulaval.glo2004.afficheur.FramePrincipal;
import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.afficheur.onglets.OngletCarte;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jonathan
 */
public class StatsCartePanel extends javax.swing.JPanel {
    
    private OngletCarte onglet;
    
    public StatsCartePanel() {
        initComponents();
        
        try {
            StatsLabel.setFont(FontRegister.RobotoThin.deriveFont(21f));
            Main.setBackground(new Color(216, 222, 233, 38));
            DeleteButton.setBackground(new Color(216, 222, 233, 38));
            DeleteButton.setFont(FontRegister.RobotoLight.deriveFont(15f));
            ModifyButton.setBackground(new Color(216, 222, 233, 38));
            ModifyButton.setFont(FontRegister.RobotoLight.deriveFont(15f));
        }
        catch(Exception e) {
        }
    }
    
    public void setOnglet(OngletCarte onglet) {
        this.onglet = onglet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new ca.ulaval.glo2004.afficheur.PanelArrondi();
        StatsHeader = new javax.swing.JPanel();
        StatsLabel = new javax.swing.JLabel();
        Buttons = new javax.swing.JPanel();
        DeleteButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 25));

        Main.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 25, 15));
        Main.setLayout(new java.awt.BorderLayout());

        StatsHeader.setOpaque(false);
        StatsHeader.setLayout(new java.awt.BorderLayout());

        StatsLabel.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        StatsLabel.setText("Statistiques");
        StatsHeader.add(StatsLabel, java.awt.BorderLayout.CENTER);

        Main.add(StatsHeader, java.awt.BorderLayout.NORTH);

        add(Main, java.awt.BorderLayout.CENTER);

        Buttons.setOpaque(false);
        Buttons.setPreferredSize(new java.awt.Dimension(100, 50));
        Buttons.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        DeleteButton.setText("Supprimer");
        DeleteButton.setFocusable(false);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseReleased(evt);
            }
        });
        Buttons.add(DeleteButton);

        ModifyButton.setText("Modifier");
        ModifyButton.setFocusable(false);
        ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseReleased(evt);
            }
        });
        Buttons.add(ModifyButton);

        add(Buttons, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseReleased
        onglet.goToCreationCarte();
    }//GEN-LAST:event_ModifyButtonMouseReleased

    private void DeleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseReleased
        onglet.retirerCourant();
    }//GEN-LAST:event_DeleteButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton DeleteButton;
    private ca.ulaval.glo2004.afficheur.PanelArrondi Main;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JPanel StatsHeader;
    private javax.swing.JLabel StatsLabel;
    // End of variables declaration//GEN-END:variables
}
