/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.panels;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.afficheur.objetsUI.ObjetMaladie;
import ca.ulaval.glo2004.afficheur.onglets.OngletMaladie;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Jonathan
 */
public class StatsMaladiePanel extends javax.swing.JPanel {
    
    private OngletMaladie onglet;
    
    public StatsMaladiePanel() {
        initComponents();
        
        try {
            MaladieInput.setFont(FontRegister.RobotoThin.deriveFont(21f));
            Main.setBackground(new Color(216, 222, 233, 38));
        }
        catch(Exception e) {
        }
    }
    
    public void setNomMaladie(String nom) {
       MaladieInput.setText(nom);
    }
    
    public void setOnglet(OngletMaladie onglet) {
        this.onglet = onglet;
    }
    
    private void sauvegarderMaladie() {
        ObjetMaladie maladie = (ObjetMaladie)onglet.getCourant();
        maladie.setNom(MaladieInput.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new ca.ulaval.glo2004.afficheur.PanelArrondi();
        StatsHeader = new javax.swing.JPanel();
        MaladieInput = new javax.swing.JTextField();
        Boutons = new javax.swing.JPanel();
        Space = new javax.swing.JPanel();
        Delete = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        Buttons = new javax.swing.JPanel();
        DeleteButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();

        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        Main.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 25, 15));
        Main.setLayout(new java.awt.BorderLayout());

        StatsHeader.setOpaque(false);
        StatsHeader.setLayout(new java.awt.BorderLayout());

        MaladieInput.setBackground(new java.awt.Color(71, 76, 88));
        MaladieInput.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        MaladieInput.setText("Nom de la maladie");
        MaladieInput.setEnabled(false);
        MaladieInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MaladieInputKeyReleased(evt);
            }
        });
        StatsHeader.add(MaladieInput, java.awt.BorderLayout.CENTER);

        Boutons.setOpaque(false);
        Boutons.setLayout(new javax.swing.BoxLayout(Boutons, javax.swing.BoxLayout.LINE_AXIS));

        Space.setOpaque(false);
        Boutons.add(Space);

        Delete.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_can_20px.png"))); // NOI18N
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Boutons.add(Delete);

        StatsHeader.add(Boutons, java.awt.BorderLayout.LINE_END);

        Main.add(StatsHeader, java.awt.BorderLayout.NORTH);

        Parent.setOpaque(false);

        javax.swing.GroupLayout ParentLayout = new javax.swing.GroupLayout(Parent);
        Parent.setLayout(ParentLayout);
        ParentLayout.setHorizontalGroup(
            ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        ParentLayout.setVerticalGroup(
            ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        Main.add(Parent, java.awt.BorderLayout.CENTER);

        add(Main);

        Buttons.setOpaque(false);
        Buttons.setPreferredSize(new java.awt.Dimension(691, 431));
        Buttons.setLayout(new java.awt.GridLayout(2, 1, 0, 25));

        DeleteButton.setText("Supprimer");
        DeleteButton.setToolTipText("Supprimer la maladie");
        DeleteButton.setFocusable(false);
        DeleteButton.setMaximumSize(new java.awt.Dimension(75, 22));
        DeleteButton.setMinimumSize(new java.awt.Dimension(75, 22));
        DeleteButton.setPreferredSize(new java.awt.Dimension(75, 22));
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseReleased(evt);
            }
        });
        Buttons.add(DeleteButton);

        ModifyButton.setText("Modifier");
        ModifyButton.setToolTipText("Modifier la maladie");
        ModifyButton.setFocusable(false);
        ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseReleased(evt);
            }
        });
        Buttons.add(ModifyButton);

        add(Buttons);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        onglet.retirerCourant();
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseReleased
        
    }//GEN-LAST:event_DeleteButtonMouseReleased

    private void ModifyButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseReleased
        if(onglet.getCardLocked()) { // En modification, mais bouton agis comme sauvegarde
            ModifyButton.setText("Modifier");
            ModifyButton.setToolTipText("Modifier les informations");
            enableFields(false);
            // Sauvegarde
            
            //updateUI();

            sauvegarderMaladie();
            
        } else {
            ModifyButton.setText("Enregistrer");
            ModifyButton.setToolTipText("Enregistrer les informations");
            enableFields(true);
        }
    }//GEN-LAST:event_ModifyButtonMouseReleased

    private void MaladieInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaladieInputKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.requestFocusInWindow();
            updateUI();

            sauvegarderMaladie();
        }
    }//GEN-LAST:event_MaladieInputKeyReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        this.requestFocusInWindow();
        updateUI();
    }//GEN-LAST:event_formMouseReleased

    private void enableFields(boolean enabled) {
        onglet.setCardLocked(enabled);
        MaladieInput.setEnabled(enabled);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boutons;
    private javax.swing.JPanel Buttons;
    private javax.swing.JLabel Delete;
    private javax.swing.JButton DeleteButton;
    private ca.ulaval.glo2004.afficheur.PanelArrondi Main;
    private javax.swing.JTextField MaladieInput;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Space;
    private javax.swing.JPanel StatsHeader;
    // End of variables declaration//GEN-END:variables
}
