/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import java.awt.Color;

/**
 *
 * @author Jonathan
 */
public class CarteScenarioPanel extends PanelArrondi {

    /**
     * Creates new form ScenarioMapPanel
     */
    public CarteScenarioPanel() {
        initComponents();
        
        setBackground(new Color(216, 222, 233, 38));
        try {
            MapNameLabel.setFont(FontRegister.RobotoThin.deriveFont(21f));
        }
        catch(Exception e) {
        }
    }
    
    public void setMapName(String text) {
        MapNameLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MapPanelHeader = new javax.swing.JPanel();
        MapNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.BorderLayout());

        MapPanelHeader.setOpaque(false);
        MapPanelHeader.setLayout(new java.awt.BorderLayout());

        MapNameLabel.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        MapNameLabel.setText("Nom de la carte");
        MapPanelHeader.add(MapNameLabel, java.awt.BorderLayout.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_upload_20px.png"))); // NOI18N
        MapPanelHeader.add(jLabel2, java.awt.BorderLayout.EAST);

        add(MapPanelHeader, java.awt.BorderLayout.NORTH);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MapNameLabel;
    private javax.swing.JPanel MapPanelHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
