/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

/**
 *
 * @author Jonathan
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabMenu = new javax.swing.JTabbedPane();
        TitleMenu = new javax.swing.JPanel();
        ScenarioTab = new ca.ulaval.glo2004.afficheur.OngletScenario();
        MapTab = new ca.ulaval.glo2004.afficheur.OngletCarte();
        jPanel2 = new javax.swing.JPanel();
        QuitButton = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        TabMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TabMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabMenuMousePressed(evt);
            }
        });

        TitleMenu.setBackground(new java.awt.Color(46, 52, 64));
        TitleMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TitleMenu.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout TitleMenuLayout = new javax.swing.GroupLayout(TitleMenu);
        TitleMenu.setLayout(TitleMenuLayout);
        TitleMenuLayout.setHorizontalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TitleMenuLayout.setVerticalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/Logo3.130FINAL.png")), TitleMenu, "Accueil"); // NOI18N
        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_play_40px.png")), ScenarioTab); // NOI18N
        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_country_40px.png")), MapTab); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_microorganisms_40px.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout QuitButtonLayout = new javax.swing.GroupLayout(QuitButton);
        QuitButton.setLayout(QuitButtonLayout);
        QuitButtonLayout.setHorizontalGroup(
            QuitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        QuitButtonLayout.setVerticalGroup(
            QuitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_35px.png")), QuitButton); // NOI18N

        add(TabMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TabMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabMenuMousePressed
        if (TabMenu.getSelectedIndex() == TabMenu.getTabCount() - 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_TabMenuMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.ulaval.glo2004.afficheur.OngletCarte MapTab;
    private javax.swing.JPanel QuitButton;
    private ca.ulaval.glo2004.afficheur.OngletScenario ScenarioTab;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JPanel TitleMenu;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
