/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;

/**
 *
 * @author Jonathan
 */
public class PanelArrondi extends javax.swing.JPanel {
    
    private Color bgColor, borderColor;
    private final Dimension arcs = new Dimension(20,20);
    
    protected final Color defaultColor = new Color(71, 76, 88);
    
    public PanelArrondi() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        if (this.isOpaque()) {
            int width = getWidth();
            int height = getHeight();
            
            Graphics2D graphics = (Graphics2D) g.create();
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            graphics.setColor(bgColor);
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);

            graphics.setColor(borderColor);
            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);
            
            graphics.dispose();
        }
    }
    
    @Override
    public void setBackground(Color color) {
        bgColor = color;
    }
    
    protected void setBorderColor(Color color) {
        borderColor = color;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
