/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import java.awt.Color;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jonathan
 */
public class ScenarioTab extends javax.swing.JPanel {

    private ArrayList<SimulationCard> simulationCards = new ArrayList<SimulationCard>(); 
    private SimulationCard currentToggled;
    
    public ScenarioTab() {
        initComponents();
        
        try {
            addSimulationCard();
        
            ScenariosScrollPane.getHorizontalScrollBar().setUnitIncrement(10);

            ScenariosLabel.setFont(FontRegister.RobotoThin.deriveFont(25f));
            Sce_InformationsLabel.setFont(FontRegister.RobotoThin.deriveFont(25f));
            AddScenarioButton.setBackground(new Color(216, 222, 233, 38));
            ImportScenarioButton.setBackground(new Color(216, 222, 233, 38));
            
            scenarioStatsPanel1.setScenarioTab(this);
        } catch (Exception e) {
        }
        
    }
    
    public void addSimulationCard() {
        SimulationCard card = new SimulationCard(this);
        card.setSimulationName("" + simulationCards.size());
        simulationCards.add(card);
        if (simulationCards.size() == 1) {
            onSimulationCardClicked(card);
        }
        ProjectPanelContainer.add(card);
        updateUI();
    }
    
    public void onStartSimulation() {
        JOptionPane optionPane = new JOptionPane();
        optionPane.setMessage("Voulez-vous commencer cette simulation?");
        optionPane.setMessageType(JOptionPane.QUESTION_MESSAGE);
        optionPane.setOptionType(JOptionPane.YES_NO_CANCEL_OPTION);
        
        int result = JOptionPane.showOptionDialog(
            SwingUtilities.windowForComponent(this),
            optionPane.getMessage(),
            "Commencer la simulation?",
            optionPane.getOptionType(),
            optionPane.getMessageType(),
            optionPane.getIcon(),
            optionPane.getOptions(),
            optionPane.getInitialValue());
        
        if (result == JOptionPane.YES_OPTION) {
            System.out.println("start");
        }
    }
    
    public void removeSimulationCard() {
        simulationCards.remove(currentToggled);
        ProjectPanelContainer.remove(currentToggled);
        updateUI();
        
        if (!simulationCards.isEmpty()) {
            onSimulationCardClicked(simulationCards.get(0));
        }
    }
    
    public void onSimulationCardClicked(SimulationCard card) {
        if (currentToggled != null &&
            card != currentToggled) {
            currentToggled.setToggled(false);
        }
        
        currentToggled = card;
        
        // Voir dans la liste et toggle le bon avec le bon index
        currentToggled.setToggled(true);
        
        scenarioMapPanel2.setMapName(currentToggled.getSimulationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scenarios = new javax.swing.JPanel();
        ScenariosTitle = new javax.swing.JPanel();
        ScenariosLabel = new javax.swing.JLabel();
        AddScenarioButton = new javax.swing.JButton();
        ImportScenarioButton = new javax.swing.JButton();
        ScenariosScrollPane = new javax.swing.JScrollPane();
        ProjectPanelContainer = new javax.swing.JPanel();
        Sce_Informations = new javax.swing.JPanel();
        Sce_InformationsLabel = new javax.swing.JLabel();
        Layout5 = new ca.ulaval.glo2004.afficheur.RoundedPanel();
        scenarioMapPanel2 = new ca.ulaval.glo2004.afficheur.ScenarioMapPanel();
        scenarioStatsPanel1 = new ca.ulaval.glo2004.afficheur.ScenarioStatsPanel();

        setBackground(new java.awt.Color(46, 52, 64));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 35, 35));
        setLayout(new java.awt.BorderLayout());

        Scenarios.setBackground(new java.awt.Color(46, 52, 64));
        Scenarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 0, 0, 0));
        Scenarios.setLayout(new java.awt.BorderLayout());

        ScenariosTitle.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosTitle.setMaximumSize(new java.awt.Dimension(974, 50));
        ScenariosTitle.setMinimumSize(new java.awt.Dimension(974, 50));
        ScenariosTitle.setPreferredSize(new java.awt.Dimension(974, 35));

        ScenariosLabel.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ScenariosLabel.setText("Scénarios");
        ScenariosLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        AddScenarioButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddScenarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_math_20px.png"))); // NOI18N
        AddScenarioButton.setFocusable(false);
        AddScenarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddScenarioButton.setMaximumSize(new java.awt.Dimension(75, 30));
        AddScenarioButton.setMinimumSize(new java.awt.Dimension(75, 30));
        AddScenarioButton.setPreferredSize(new java.awt.Dimension(100, 36));
        AddScenarioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddScenarioButtonMouseClicked(evt);
            }
        });

        ImportScenarioButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ImportScenarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_installing_updates_20px.png"))); // NOI18N
        ImportScenarioButton.setFocusable(false);
        ImportScenarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImportScenarioButton.setMaximumSize(new java.awt.Dimension(75, 30));
        ImportScenarioButton.setMinimumSize(new java.awt.Dimension(75, 30));
        ImportScenarioButton.setPreferredSize(new java.awt.Dimension(100, 36));

        javax.swing.GroupLayout ScenariosTitleLayout = new javax.swing.GroupLayout(ScenariosTitle);
        ScenariosTitle.setLayout(ScenariosTitleLayout);
        ScenariosTitleLayout.setHorizontalGroup(
            ScenariosTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addComponent(ScenariosLabel)
                .addGap(20, 20, 20)
                .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImportScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ScenariosTitleLayout.setVerticalGroup(
            ScenariosTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(ScenariosLabel))
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(ImportScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Scenarios.add(ScenariosTitle, java.awt.BorderLayout.NORTH);

        ScenariosScrollPane.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        ScenariosScrollPane.setMaximumSize(new java.awt.Dimension(75, 250));
        ScenariosScrollPane.setMinimumSize(new java.awt.Dimension(75, 250));
        ScenariosScrollPane.setPreferredSize(new java.awt.Dimension(75, 250));

        ProjectPanelContainer.setBackground(new java.awt.Color(46, 52, 64));
        ProjectPanelContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, -25, 0, 0));
        ProjectPanelContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 25, 5));
        ScenariosScrollPane.setViewportView(ProjectPanelContainer);

        Scenarios.add(ScenariosScrollPane, java.awt.BorderLayout.CENTER);

        add(Scenarios, java.awt.BorderLayout.NORTH);

        Sce_Informations.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 0, 0, 0));
        Sce_Informations.setOpaque(false);
        Sce_Informations.setLayout(new java.awt.BorderLayout());

        Sce_InformationsLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Sce_InformationsLabel.setText("Informations");
        Sce_InformationsLabel.setMaximumSize(new java.awt.Dimension(146, 35));
        Sce_InformationsLabel.setMinimumSize(new java.awt.Dimension(146, 35));
        Sce_InformationsLabel.setPreferredSize(new java.awt.Dimension(146, 35));
        Sce_Informations.add(Sce_InformationsLabel, java.awt.BorderLayout.NORTH);

        Layout5.setBackground(new java.awt.Color(46, 52, 64));
        Layout5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        Layout5.setLayout(new java.awt.GridLayout(1, 2, 25, 0));
        Layout5.add(scenarioMapPanel2);
        Layout5.add(scenarioStatsPanel1);

        Sce_Informations.add(Layout5, java.awt.BorderLayout.CENTER);

        add(Sce_Informations, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void AddScenarioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddScenarioButtonMouseClicked
        addSimulationCard();
    }//GEN-LAST:event_AddScenarioButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddScenarioButton;
    private javax.swing.JButton ImportScenarioButton;
    private ca.ulaval.glo2004.afficheur.RoundedPanel Layout5;
    private javax.swing.JPanel ProjectPanelContainer;
    private javax.swing.JPanel Sce_Informations;
    private javax.swing.JLabel Sce_InformationsLabel;
    private javax.swing.JPanel Scenarios;
    private javax.swing.JLabel ScenariosLabel;
    private javax.swing.JScrollPane ScenariosScrollPane;
    private javax.swing.JPanel ScenariosTitle;
    private ca.ulaval.glo2004.afficheur.ScenarioMapPanel scenarioMapPanel2;
    private ca.ulaval.glo2004.afficheur.ScenarioStatsPanel scenarioStatsPanel1;
    // End of variables declaration//GEN-END:variables
}
