/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import java.awt.Color;
import javax.swing.UIManager;


/**
 * Adapte depuis https://stackoverflow.com/questions/15025092/border-with-rounded-corners-transparency
 * @author Jonathan
 */
public class SimulationCard extends RoundedPanel {
    private boolean toggled = false;
    private final ScenarioTab tab;
    
    public SimulationCard(ScenarioTab tab) {
        this.tab = tab;
        UIManager.put("ProgressBar.arc", 999);
        initComponents();
        
        SimulationName.setFont(FontRegister.RobotoRegular.deriveFont(21.3062f));
        Day.setFont(FontRegister.RobotoLight.deriveFont(15.98f));
        MapName.setFont(FontRegister.RobotoLight.deriveFont(12f));
        VirusName.setFont(FontRegister.RobotoLight.deriveFont(12f));
        
        // Rend le panel translucide
        setBackground(defaultColor);
    }
    
    public void setSimulationName(String name) {
        SimulationName.setText(name);
    }
    
    public void setDays(String days) {
        Day.setText(days);
    }
    
    public void setMapName(String name) {
        MapName.setText(name);
    }
    
    public String getMapName() {
        return MapName.getText();
    }
    
    public void setVirusName(String name) {
        VirusName.setText(name);
    }
    
    public void setInfectedPercent(int percent) {
        InfectedProgressBar.setValue(percent);
    }
    
    public void setCuredPercent(int percent) {
        CuredProgressBar.setValue(percent);
    }
    
    public void setImmunedPercent(int percent) {
        ImmunedProgressBar.setValue(percent);
    }
    
    public void setDeadPercent(int percent) {
        DeadProgressBar.setValue(percent);
    }
    
    public void setToggled(boolean toggled) {
        this.toggled = toggled;
        if (toggled) {
            setBackground(new Color(104,125,135));
            setBorderColor(new Color(136, 192, 208));
        }
        else {
            setBackground(defaultColor);
            setBorderColor(defaultColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SimulationName = new javax.swing.JLabel();
        Day = new javax.swing.JLabel();
        DiagramPanel = new javax.swing.JPanel();
        Bars = new javax.swing.JPanel();
        InfectedProgressBar = new javax.swing.JProgressBar();
        CuredProgressBar = new javax.swing.JProgressBar();
        ImmunedProgressBar = new javax.swing.JProgressBar();
        DeadProgressBar = new javax.swing.JProgressBar();
        MapName = new javax.swing.JLabel();
        VirusName = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(351, 215));
        setMinimumSize(new java.awt.Dimension(351, 215));
        setPreferredSize(new java.awt.Dimension(351, 215));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        SimulationName.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        SimulationName.setText("Nom de la simulation");

        Day.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Day.setText("Jour 238");
        Day.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Day.setBorder(javax.swing.BorderFactory.createEmptyBorder(-1, -1, -1, -1));
        Day.setIconTextGap(0);

        DiagramPanel.setBackground(new java.awt.Color(59, 66, 82));
        DiagramPanel.setMaximumSize(new java.awt.Dimension(349, 85));
        DiagramPanel.setMinimumSize(new java.awt.Dimension(349, 85));
        DiagramPanel.setPreferredSize(new java.awt.Dimension(349, 85));

        Bars.setBackground(new java.awt.Color(59, 66, 82));
        Bars.setLayout(new java.awt.GridLayout(4, 0));

        InfectedProgressBar.setBackground(new java.awt.Color(59, 66, 82));
        InfectedProgressBar.setForeground(new java.awt.Color(191, 97, 106));
        InfectedProgressBar.setValue(25);
        InfectedProgressBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        InfectedProgressBar.setBorderPainted(false);
        Bars.add(InfectedProgressBar);

        CuredProgressBar.setBackground(new java.awt.Color(59, 66, 82));
        CuredProgressBar.setForeground(new java.awt.Color(163, 190, 140));
        CuredProgressBar.setValue(100);
        CuredProgressBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        CuredProgressBar.setBorderPainted(false);
        Bars.add(CuredProgressBar);

        ImmunedProgressBar.setBackground(new java.awt.Color(59, 66, 82));
        ImmunedProgressBar.setForeground(new java.awt.Color(136, 192, 208));
        ImmunedProgressBar.setValue(75);
        ImmunedProgressBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        ImmunedProgressBar.setBorderPainted(false);
        Bars.add(ImmunedProgressBar);

        DeadProgressBar.setBackground(new java.awt.Color(59, 66, 82));
        DeadProgressBar.setForeground(new java.awt.Color(180, 142, 173));
        DeadProgressBar.setValue(50);
        DeadProgressBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        DeadProgressBar.setBorderPainted(false);
        Bars.add(DeadProgressBar);

        javax.swing.GroupLayout DiagramPanelLayout = new javax.swing.GroupLayout(DiagramPanel);
        DiagramPanel.setLayout(DiagramPanelLayout);
        DiagramPanelLayout.setHorizontalGroup(
            DiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Bars, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DiagramPanelLayout.setVerticalGroup(
            DiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MapName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        MapName.setText("Nom de la carte");

        VirusName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        VirusName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        VirusName.setText("Nom du virus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SimulationName, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(MapName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VirusName)
                .addGap(41, 41, 41))
            .addComponent(DiagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SimulationName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Day)
                .addGap(14, 14, 14)
                .addComponent(DiagramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MapName)
                    .addComponent(VirusName))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        if (!toggled) {
            setBackground(new Color(104,125,135));
        }
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (!toggled) {
            setBackground(defaultColor);
        }
    }//GEN-LAST:event_formMouseExited

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (!toggled) {
          tab.onSimulationCardClicked(this);  
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bars;
    private javax.swing.JProgressBar CuredProgressBar;
    private javax.swing.JLabel Day;
    private javax.swing.JProgressBar DeadProgressBar;
    private javax.swing.JPanel DiagramPanel;
    private javax.swing.JProgressBar ImmunedProgressBar;
    private javax.swing.JProgressBar InfectedProgressBar;
    private javax.swing.JLabel MapName;
    private javax.swing.JLabel SimulationName;
    private javax.swing.JLabel VirusName;
    // End of variables declaration//GEN-END:variables
}
