/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jonathan
 */
public class Simulation extends javax.swing.JPanel {

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
        
        SidePanel.setBackground(SidePanel.defaultColor);
        LinkButton.setIcon("/icons/icons8_chain_40px.png");
        StatsButton.setIcon("/icons/icons8_bar_chart_40px.png");
        HelpButton.setIcon("/icons/icons8_help_40px.png");
        HomeButton.setIcon("/icons/icons8_home_40px.png");
        
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HomeButtonReleased(evt);
            }
        });
    }
    
    private void HomeButtonReleased(MouseEvent evt) {
        JOptionPane optionPane = new JOptionPane();
        optionPane.setMessage("Retourner au menu principal?");
        optionPane.setMessageType(JOptionPane.QUESTION_MESSAGE);
        optionPane.setOptionType(JOptionPane.YES_NO_CANCEL_OPTION);
        
        int result = JOptionPane.showOptionDialog(
            SwingUtilities.windowForComponent(this),
            optionPane.getMessage(),
            "Retour au menu?",
            optionPane.getOptionType(),
            optionPane.getMessageType(),
            optionPane.getIcon(),
            optionPane.getOptions(),
            optionPane.getInitialValue());
        
        if (result == JOptionPane.YES_OPTION) {
            FramePrincipal frame = (FramePrincipal)SwingUtilities.windowForComponent(this);
            frame.returnToHome();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slider = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        Buttons = new javax.swing.JPanel();
        SidePanel = new ca.ulaval.glo2004.afficheur.RoundedPanel();
        AddButton = new ca.ulaval.glo2004.afficheur.SimulationBouton();
        LinkButton = new ca.ulaval.glo2004.afficheur.SimulationBouton();
        Spacing = new javax.swing.JPanel();
        StatsButton = new ca.ulaval.glo2004.afficheur.SimulationBouton();
        HelpButton = new ca.ulaval.glo2004.afficheur.SimulationBouton();
        HomeButton = new ca.ulaval.glo2004.afficheur.SimulationBouton();

        setBackground(new java.awt.Color(46, 52, 64));
        setLayout(new javax.swing.OverlayLayout(this));

        Slider.setOpaque(false);

        javax.swing.GroupLayout SliderLayout = new javax.swing.GroupLayout(Slider);
        Slider.setLayout(SliderLayout);
        SliderLayout.setHorizontalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                .addContainerGap())
        );
        SliderLayout.setVerticalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SliderLayout.createSequentialGroup()
                .addContainerGap(678, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(Slider);

        Buttons.setBackground(new java.awt.Color(46, 52, 64));
        Buttons.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Buttons.setOpaque(false);

        SidePanel.setMaximumSize(new java.awt.Dimension(100, 200));
        SidePanel.setMinimumSize(new java.awt.Dimension(100, 200));
        SidePanel.setPreferredSize(new java.awt.Dimension(100, 200));
        SidePanel.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        AddButton.setBorder(null);
        AddButton.setMaximumSize(new java.awt.Dimension(50, 50));
        AddButton.setMinimumSize(new java.awt.Dimension(50, 50));
        AddButton.setPreferredSize(new java.awt.Dimension(50, 50));
        SidePanel.add(AddButton);

        LinkButton.setBorder(null);
        LinkButton.setMaximumSize(new java.awt.Dimension(50, 50));
        LinkButton.setMinimumSize(new java.awt.Dimension(50, 50));
        LinkButton.setPreferredSize(new java.awt.Dimension(50, 50));
        SidePanel.add(LinkButton);

        Spacing.setBackground(new java.awt.Color(90, 95, 104));
        Spacing.setOpaque(false);
        Spacing.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout SpacingLayout = new javax.swing.GroupLayout(Spacing);
        Spacing.setLayout(SpacingLayout);
        SpacingLayout.setHorizontalGroup(
            SpacingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        SpacingLayout.setVerticalGroup(
            SpacingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        SidePanel.add(Spacing);

        StatsButton.setBorder(null);
        StatsButton.setMaximumSize(new java.awt.Dimension(50, 50));
        StatsButton.setMinimumSize(new java.awt.Dimension(50, 50));
        StatsButton.setPreferredSize(new java.awt.Dimension(50, 50));
        SidePanel.add(StatsButton);

        HelpButton.setBorder(null);
        HelpButton.setMaximumSize(new java.awt.Dimension(50, 50));
        HelpButton.setMinimumSize(new java.awt.Dimension(50, 50));
        HelpButton.setPreferredSize(new java.awt.Dimension(50, 50));
        SidePanel.add(HelpButton);

        HomeButton.setBorder(null);
        HomeButton.setMaximumSize(new java.awt.Dimension(50, 50));
        HomeButton.setMinimumSize(new java.awt.Dimension(50, 50));
        HomeButton.setPreferredSize(new java.awt.Dimension(50, 50));
        SidePanel.add(HomeButton);

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 877, Short.MAX_VALUE))
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        add(Buttons);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.ulaval.glo2004.afficheur.SimulationBouton AddButton;
    private javax.swing.JPanel Buttons;
    private ca.ulaval.glo2004.afficheur.SimulationBouton HelpButton;
    private ca.ulaval.glo2004.afficheur.SimulationBouton HomeButton;
    private ca.ulaval.glo2004.afficheur.SimulationBouton LinkButton;
    private ca.ulaval.glo2004.afficheur.RoundedPanel SidePanel;
    private javax.swing.JPanel Slider;
    private javax.swing.JPanel Spacing;
    private ca.ulaval.glo2004.afficheur.SimulationBouton StatsButton;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
