/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Jonathan
 */
public class ZoomInfoPanel extends PanelArrondi implements ActionListener {
    
    private final Timer timer;
    
    public ZoomInfoPanel() {
        initComponents();
        timer = new Timer(3000, this);
        
        try {

            ZoomLabel.setFont(FontRegister.RobotoLight.deriveFont(24f));

            this.setVisible(false);
        }
        catch (Exception e) {}
    }
    
    public void onMouseWheel(double zoomFactor) {
        if (!this.isVisible()) {
            this.setVisible(true);
        }
        
        ZoomLabel.setText(String.format("%.2fx", zoomFactor));
        revalidate();
        
        timer.restart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZoomLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        ZoomLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ZoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ZoomLabel.setText("1.00x");
        ZoomLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8));
        add(ZoomLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ZoomLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        this.setVisible(false);
    }
}
