/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004;

import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author henri
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuContainer = new javax.swing.JPanel();
        SideMenuContainer = new javax.swing.JPanel();
        LogoTitleContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PlayContainer = new javax.swing.JPanel();
        PlayIcon = new javax.swing.JLabel();
        PlayIndex = new javax.swing.JPanel();
        MapButtonContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        MapIndex = new javax.swing.JPanel();
        VirusButtonContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VirusIndex = new javax.swing.JPanel();
        AddButtonContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AddIndex = new javax.swing.JPanel();
        ExitButtonContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ItemsMenuContainer = new javax.swing.JPanel();
        ItemTitleContainer = new javax.swing.JPanel();
        ItemTitle = new javax.swing.JLabel();
        ItemsScrollPane = new javax.swing.JScrollPane();
        ItemsContainer = new javax.swing.JPanel();
        TitleMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 780));
        setSize(new java.awt.Dimension(1280, 780));

        MenuContainer.setBackground(new java.awt.Color(46, 52, 64));
        MenuContainer.setMinimumSize(new java.awt.Dimension(600, 720));

        SideMenuContainer.setBackground(new java.awt.Color(59, 66, 82));
        SideMenuContainer.setMinimumSize(new java.awt.Dimension(200, 720));

        LogoTitleContainer.setBackground(new java.awt.Color(59, 66, 82));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simudemie_logo_100px_63px.png"))); // NOI18N

        javax.swing.GroupLayout LogoTitleContainerLayout = new javax.swing.GroupLayout(LogoTitleContainer);
        LogoTitleContainer.setLayout(LogoTitleContainerLayout);
        LogoTitleContainerLayout.setHorizontalGroup(
            LogoTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoTitleContainerLayout.setVerticalGroup(
            LogoTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        PlayContainer.setBackground(new java.awt.Color(59, 66, 82));
        PlayContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayIcon.setBackground(new java.awt.Color(59, 66, 82));
        PlayIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_play_25px.png"))); // NOI18N
        PlayContainer.add(PlayIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        PlayIndex.setBackground(new java.awt.Color(59, 66, 82));

        javax.swing.GroupLayout PlayIndexLayout = new javax.swing.GroupLayout(PlayIndex);
        PlayIndex.setLayout(PlayIndexLayout);
        PlayIndexLayout.setHorizontalGroup(
            PlayIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PlayIndexLayout.setVerticalGroup(
            PlayIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PlayContainer.add(PlayIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        MapButtonContainer.setBackground(new java.awt.Color(59, 66, 82));
        MapButtonContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(59, 66, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_map_25px.png"))); // NOI18N
        MapButtonContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        MapIndex.setBackground(new java.awt.Color(59, 66, 82));

        javax.swing.GroupLayout MapIndexLayout = new javax.swing.GroupLayout(MapIndex);
        MapIndex.setLayout(MapIndexLayout);
        MapIndexLayout.setHorizontalGroup(
            MapIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        MapIndexLayout.setVerticalGroup(
            MapIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        MapButtonContainer.add(MapIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        VirusButtonContainer.setBackground(new java.awt.Color(59, 66, 82));
        VirusButtonContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_coronavirus_25px.png"))); // NOI18N
        VirusButtonContainer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        VirusIndex.setBackground(new java.awt.Color(59, 66, 82));

        javax.swing.GroupLayout VirusIndexLayout = new javax.swing.GroupLayout(VirusIndex);
        VirusIndex.setLayout(VirusIndexLayout);
        VirusIndexLayout.setHorizontalGroup(
            VirusIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        VirusIndexLayout.setVerticalGroup(
            VirusIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        VirusButtonContainer.add(VirusIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        AddButtonContainer.setBackground(new java.awt.Color(59, 66, 82));
        AddButtonContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_add_25px.png"))); // NOI18N
        AddButtonContainer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        AddIndex.setBackground(new java.awt.Color(59, 66, 82));

        javax.swing.GroupLayout AddIndexLayout = new javax.swing.GroupLayout(AddIndex);
        AddIndex.setLayout(AddIndexLayout);
        AddIndexLayout.setHorizontalGroup(
            AddIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        AddIndexLayout.setVerticalGroup(
            AddIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        AddButtonContainer.add(AddIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        ExitButtonContainer.setBackground(new java.awt.Color(59, 66, 82));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_exit_25px.png"))); // NOI18N

        javax.swing.GroupLayout ExitButtonContainerLayout = new javax.swing.GroupLayout(ExitButtonContainer);
        ExitButtonContainer.setLayout(ExitButtonContainerLayout);
        ExitButtonContainerLayout.setHorizontalGroup(
            ExitButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ExitButtonContainerLayout.setVerticalGroup(
            ExitButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SideMenuContainerLayout = new javax.swing.GroupLayout(SideMenuContainer);
        SideMenuContainer.setLayout(SideMenuContainerLayout);
        SideMenuContainerLayout.setHorizontalGroup(
            SideMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MapButtonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddButtonContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VirusButtonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExitButtonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoTitleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideMenuContainerLayout.setVerticalGroup(
            SideMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuContainerLayout.createSequentialGroup()
                .addComponent(LogoTitleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(PlayContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MapButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VirusButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(ExitButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ItemsMenuContainer.setBackground(new java.awt.Color(46, 52, 64));
        ItemsMenuContainer.setMinimumSize(new java.awt.Dimension(400, 720));
        ItemsMenuContainer.setPreferredSize(new java.awt.Dimension(1080, 720));

        ItemTitleContainer.setBackground(new java.awt.Color(46, 52, 64));

        ItemTitle.setBackground(new java.awt.Color(46, 52, 64));
        ItemTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ItemTitle.setForeground(new java.awt.Color(236, 239, 244));
        ItemTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItemTitle.setText("Scénarios");

        javax.swing.GroupLayout ItemTitleContainerLayout = new javax.swing.GroupLayout(ItemTitleContainer);
        ItemTitleContainer.setLayout(ItemTitleContainerLayout);
        ItemTitleContainerLayout.setHorizontalGroup(
            ItemTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        ItemTitleContainerLayout.setVerticalGroup(
            ItemTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ItemsScrollPane.setBackground(new java.awt.Color(46, 52, 64));
        ItemsScrollPane.setMaximumSize(new java.awt.Dimension(100, 100));
        ItemsScrollPane.setMinimumSize(new java.awt.Dimension(100, 100));

        ItemsContainer.setBackground(new java.awt.Color(46, 52, 64));
        ItemsScrollPane.setViewportView(ItemsContainer);

        javax.swing.GroupLayout ItemsMenuContainerLayout = new javax.swing.GroupLayout(ItemsMenuContainer);
        ItemsMenuContainer.setLayout(ItemsMenuContainerLayout);
        ItemsMenuContainerLayout.setHorizontalGroup(
            ItemsMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemsMenuContainerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ItemsMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ItemTitleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        ItemsMenuContainerLayout.setVerticalGroup(
            ItemsMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsMenuContainerLayout.createSequentialGroup()
                .addComponent(ItemTitleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ItemsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout MenuContainerLayout = new javax.swing.GroupLayout(MenuContainer);
        MenuContainer.setLayout(MenuContainerLayout);
        MenuContainerLayout.setHorizontalGroup(
            MenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuContainerLayout.createSequentialGroup()
                .addComponent(SideMenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ItemsMenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuContainerLayout.setVerticalGroup(
            MenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideMenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ItemsMenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        setJMenuBar(TitleMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void enteredColor(JPanel pane){
        pane.setBackground(new Color(76,86,106));
    }  
    
    private void setColor(JPanel pane){
        pane.setBackground(new Color(46,52,64));
    }
    
    private void underlinedColor(JPanel pane){
        pane.setBackground(new Color(136,192,208));
    }   
    
    private void resetColor(JPanel pane){
        pane.setBackground(new Color(59,66,82));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatNordIJTheme.install();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddButtonContainer;
    private javax.swing.JPanel AddIndex;
    private javax.swing.JPanel ExitButtonContainer;
    private javax.swing.JLabel ItemTitle;
    private javax.swing.JPanel ItemTitleContainer;
    private javax.swing.JPanel ItemsContainer;
    private javax.swing.JPanel ItemsMenuContainer;
    private javax.swing.JScrollPane ItemsScrollPane;
    private javax.swing.JPanel LogoTitleContainer;
    private javax.swing.JPanel MapButtonContainer;
    private javax.swing.JPanel MapIndex;
    private javax.swing.JPanel MenuContainer;
    private javax.swing.JPanel PlayContainer;
    private javax.swing.JLabel PlayIcon;
    private javax.swing.JPanel PlayIndex;
    private javax.swing.JPanel SideMenuContainer;
    private javax.swing.JMenuBar TitleMenuBar;
    private javax.swing.JPanel VirusButtonContainer;
    private javax.swing.JPanel VirusIndex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
