package ca.ulaval.glo2004;

import com.formdev.flatlaf.IntelliJTheme;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.UIManager;

public class MenuPrincipal extends javax.swing.JFrame {
    private static final String ICON_PATH = "/icons/icon_virus_64px.png";
    
    public MenuPrincipal() {
        initTabbedPaneProperties();
        initComponents();
        
        for (int i = 0; i < 4; i++) {
            ProjectPanelContainer.add(new SimulationCard());
        }
        
        ScenariosLabel.setFont(FontRegister.RobotoThin.deriveFont(25f));
    }
    
    /*
    * Doit être appelé avant la création du TabbedPane
    */
    private void initTabbedPaneProperties() {
        UIManager.put("TabbedPaneUI", "ca.ulaval.glo2004.CustomTabbedPaneUI");
        
        UIManager.put("TabbedPane.tabSelectionHeight", 5);
        UIManager.put("TabbedPane.tabAreaAlignment", "leading");
        UIManager.put("TabbedPane.tabHeight", 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        TabMenu = new javax.swing.JTabbedPane();
        TitleMenu = new javax.swing.JPanel();
        Projets = new javax.swing.JPanel();
        ScenariosLabel = new javax.swing.JLabel();
        AddScenarioButton = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        ProjectPanelContainer = new javax.swing.JPanel();
        TitleMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simudémie");
        setBackground(new java.awt.Color(0, 255, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));

        MainMenu.setBackground(new java.awt.Color(46, 52, 64));
        MainMenu.setOpaque(false);
        MainMenu.setLayout(new java.awt.BorderLayout());

        TabMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        TitleMenu.setBackground(new java.awt.Color(46, 52, 64));
        TitleMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TitleMenu.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout TitleMenuLayout = new javax.swing.GroupLayout(TitleMenu);
        TitleMenu.setLayout(TitleMenuLayout);
        TitleMenuLayout.setHorizontalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        TitleMenuLayout.setVerticalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/simudemie_logo_100px_63px.png")), TitleMenu, "Accueil"); // NOI18N

        Projets.setBackground(new java.awt.Color(46, 52, 64));
        Projets.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Projets.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        ScenariosLabel.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ScenariosLabel.setText("Scénarios");
        ScenariosLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));

        AddScenarioButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddScenarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_math_20px.png"))); // NOI18N
        AddScenarioButton.setFocusable(false);
        AddScenarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ScrollPane.setBackground(new java.awt.Color(46, 52, 64));
        ScrollPane.setBorder(null);
        ScrollPane.setMaximumSize(new java.awt.Dimension(75, 275));
        ScrollPane.setMinimumSize(new java.awt.Dimension(75, 275));
        ScrollPane.setPreferredSize(new java.awt.Dimension(75, 275));

        ProjectPanelContainer.setBackground(new java.awt.Color(46, 52, 64));
        ProjectPanelContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, -75, 0, 0));
        ProjectPanelContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 75, 5));
        ScrollPane.setViewportView(ProjectPanelContainer);

        javax.swing.GroupLayout ProjetsLayout = new javax.swing.GroupLayout(Projets);
        Projets.setLayout(ProjetsLayout);
        ProjetsLayout.setHorizontalGroup(
            ProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjetsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProjetsLayout.createSequentialGroup()
                        .addComponent(ScenariosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 778, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProjetsLayout.setVerticalGroup(
            ProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjetsLayout.createSequentialGroup()
                .addGroup(ProjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScenariosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjetsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icon_play_25px.png")), Projets, "Scénarios"); // NOI18N

        MainMenu.add(TabMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainMenu, java.awt.BorderLayout.CENTER);
        setJMenuBar(TitleMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        IntelliJTheme.install(MenuPrincipal.class.getResourceAsStream("/themes/nord.theme.json"));
        UIManager.put("RootPaneUI", "ca.ulaval.glo2004.CustomRootPaneUI");
        UIManager.put("Button.arc", 15);
        
        // TODO NE PAS CALL CA ICI
        FontRegister.register();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new MenuPrincipal();
                
		frame.dispose();
		frame.setUndecorated(true);
		frame.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
		frame.setVisible(true);

		// enable/disable window decoration for later created frames/dialogs
		frame.setDefaultLookAndFeelDecorated(true);
                frame.setIconImage(new javax.swing.ImageIcon(getClass().getResource(ICON_PATH)).getImage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddScenarioButton;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel ProjectPanelContainer;
    private javax.swing.JPanel Projets;
    private javax.swing.JLabel ScenariosLabel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JPanel TitleMenu;
    private javax.swing.JMenuBar TitleMenuBar;
    // End of variables declaration//GEN-END:variables
}
