package ca.ulaval.glo2004;

import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.UIManager;

public class MenuPrincipal extends javax.swing.JFrame {
    private static final String ICON_PATH = "/icons/icon_virus_64px.png";
    
    public MenuPrincipal() {
        initTabbedPaneProperties();
        initComponents();
        
        for (int i = 0; i < 4; i++) {
            ProjectPanelContainer.add(new SimulationCard());
        }
        
        ScenariosLabel.setFont(FontRegister.RobotoThin.deriveFont(25f));
        InformationsLabel.setFont(FontRegister.RobotoThin.deriveFont(25f));
        AddScenarioButton.setBackground(new Color(216, 222, 233, 38));
        ImportScenarioButton.setBackground(new Color(216, 222, 233, 38));
    }
    
    /*
    * Doit être appelé avant la création du TabbedPane
    */
    private void initTabbedPaneProperties() {
        UIManager.put("TabbedPaneUI", "ca.ulaval.glo2004.CustomTabbedPaneUI");
        
        UIManager.put("TabbedPane.tabSelectionHeight", 5);
        UIManager.put("TabbedPane.tabAreaAlignment", "leading");
        UIManager.put("TabbedPane.tabHeight", 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        TabMenu = new javax.swing.JTabbedPane();
        TitleMenu = new javax.swing.JPanel();
        ScenariosTab = new javax.swing.JPanel();
        Scenarios = new javax.swing.JPanel();
        ScenariosTitle = new javax.swing.JPanel();
        ScenariosLabel = new javax.swing.JLabel();
        AddScenarioButton = new javax.swing.JButton();
        ImportScenarioButton = new javax.swing.JButton();
        ScenariosScrollPane = new javax.swing.JScrollPane();
        ProjectPanelContainer = new javax.swing.JPanel();
        Informations = new javax.swing.JPanel();
        InformationsLabel = new javax.swing.JLabel();
        Layout = new ca.ulaval.glo2004.RoundedPanel();
        scenarioMapPanel1 = new ca.ulaval.glo2004.ScenarioMapPanel();
        scenarioStatsPanel1 = new ca.ulaval.glo2004.ScenarioStatsPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TitleMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simudémie");
        setBackground(new java.awt.Color(0, 255, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        MainMenu.setBackground(new java.awt.Color(46, 52, 64));
        MainMenu.setOpaque(false);
        MainMenu.setLayout(new java.awt.BorderLayout());

        TabMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        TitleMenu.setBackground(new java.awt.Color(46, 52, 64));
        TitleMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TitleMenu.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout TitleMenuLayout = new javax.swing.GroupLayout(TitleMenu);
        TitleMenu.setLayout(TitleMenuLayout);
        TitleMenuLayout.setHorizontalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        TitleMenuLayout.setVerticalGroup(
            TitleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/Logo3.150.png")), TitleMenu, "Accueil"); // NOI18N

        ScenariosTab.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 35, 35));
        ScenariosTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScenariosTab.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        ScenariosTab.setLayout(new java.awt.BorderLayout());

        Scenarios.setBackground(new java.awt.Color(46, 52, 64));
        Scenarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 0, 0, 0));
        Scenarios.setLayout(new java.awt.BorderLayout());

        ScenariosTitle.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosTitle.setMaximumSize(new java.awt.Dimension(974, 50));
        ScenariosTitle.setMinimumSize(new java.awt.Dimension(974, 50));
        ScenariosTitle.setPreferredSize(new java.awt.Dimension(974, 35));

        ScenariosLabel.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ScenariosLabel.setText("Scénarios");
        ScenariosLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        AddScenarioButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddScenarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_math_20px.png"))); // NOI18N
        AddScenarioButton.setFocusable(false);
        AddScenarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddScenarioButton.setMaximumSize(new java.awt.Dimension(75, 30));
        AddScenarioButton.setMinimumSize(new java.awt.Dimension(75, 30));
        AddScenarioButton.setPreferredSize(new java.awt.Dimension(100, 36));

        ImportScenarioButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ImportScenarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_download_20px.png"))); // NOI18N
        ImportScenarioButton.setFocusable(false);
        ImportScenarioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImportScenarioButton.setMaximumSize(new java.awt.Dimension(75, 30));
        ImportScenarioButton.setMinimumSize(new java.awt.Dimension(75, 30));
        ImportScenarioButton.setPreferredSize(new java.awt.Dimension(100, 36));

        javax.swing.GroupLayout ScenariosTitleLayout = new javax.swing.GroupLayout(ScenariosTitle);
        ScenariosTitle.setLayout(ScenariosTitleLayout);
        ScenariosTitleLayout.setHorizontalGroup(
            ScenariosTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addComponent(ScenariosLabel)
                .addGap(20, 20, 20)
                .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImportScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ScenariosTitleLayout.setVerticalGroup(
            ScenariosTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(ScenariosLabel))
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(AddScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ScenariosTitleLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(ImportScenarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Scenarios.add(ScenariosTitle, java.awt.BorderLayout.NORTH);

        ScenariosScrollPane.setBackground(new java.awt.Color(46, 52, 64));
        ScenariosScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        ScenariosScrollPane.setMaximumSize(new java.awt.Dimension(75, 250));
        ScenariosScrollPane.setMinimumSize(new java.awt.Dimension(75, 250));
        ScenariosScrollPane.setPreferredSize(new java.awt.Dimension(75, 250));

        ProjectPanelContainer.setBackground(new java.awt.Color(46, 52, 64));
        ProjectPanelContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, -49, 0, 0));
        ProjectPanelContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 50, 5));
        ScenariosScrollPane.setViewportView(ProjectPanelContainer);

        Scenarios.add(ScenariosScrollPane, java.awt.BorderLayout.CENTER);

        ScenariosTab.add(Scenarios, java.awt.BorderLayout.NORTH);

        Informations.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 0, 0, 0));
        Informations.setOpaque(false);
        Informations.setLayout(new java.awt.BorderLayout());

        InformationsLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        InformationsLabel.setText("Informations");
        InformationsLabel.setMaximumSize(new java.awt.Dimension(146, 35));
        InformationsLabel.setMinimumSize(new java.awt.Dimension(146, 35));
        InformationsLabel.setPreferredSize(new java.awt.Dimension(146, 35));
        Informations.add(InformationsLabel, java.awt.BorderLayout.NORTH);

        Layout.setBackground(new java.awt.Color(46, 52, 64));
        Layout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        Layout.setLayout(new java.awt.GridLayout(1, 2, 25, 0));
        Layout.add(scenarioMapPanel1);
        Layout.add(scenarioStatsPanel1);

        Informations.add(Layout, java.awt.BorderLayout.CENTER);

        ScenariosTab.add(Informations, java.awt.BorderLayout.CENTER);

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_play_50px.png")), ScenariosTab, "Scénarios"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_map_50px_1.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_coronavirus_50px_1.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_gallery_50px_1.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabMenu.addTab("", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_50px_2.png")), jPanel5); // NOI18N

        MainMenu.add(TabMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainMenu, java.awt.BorderLayout.CENTER);
        setJMenuBar(TitleMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        IntelliJTheme.install(MenuPrincipal.class.getResourceAsStream("/themes/nord.theme.json"));
        UIManager.put("RootPaneUI", "ca.ulaval.glo2004.CustomRootPaneUI");
        UIManager.put("Button.arc", 15);
        
        // TODO NE PAS CALL CA ICI
        FontRegister.register();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new MenuPrincipal();
                
		frame.dispose();
		frame.setUndecorated(true);
		frame.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
		frame.setVisible(true);

		// enable/disable window decoration for later created frames/dialogs
		frame.setDefaultLookAndFeelDecorated(true);
                frame.setIconImage(new javax.swing.ImageIcon(getClass().getResource(ICON_PATH)).getImage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddScenarioButton;
    private javax.swing.JButton ImportScenarioButton;
    private javax.swing.JPanel Informations;
    private javax.swing.JLabel InformationsLabel;
    private ca.ulaval.glo2004.RoundedPanel Layout;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel ProjectPanelContainer;
    private javax.swing.JPanel Scenarios;
    private javax.swing.JLabel ScenariosLabel;
    private javax.swing.JScrollPane ScenariosScrollPane;
    private javax.swing.JPanel ScenariosTab;
    private javax.swing.JPanel ScenariosTitle;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JPanel TitleMenu;
    private javax.swing.JMenuBar TitleMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private ca.ulaval.glo2004.ScenarioMapPanel scenarioMapPanel1;
    private ca.ulaval.glo2004.ScenarioStatsPanel scenarioStatsPanel1;
    // End of variables declaration//GEN-END:variables
}
