/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author Jonathan
 */
public class ProjetPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProjetPane
     */
    public ProjetPanel() {
        initComponents();
        
//        this.addComponentListener(new ComponentAdapter() {
//            public void componentResized(ComponentEvent e) {
//                int w = getWidth();
//                int h = getHeight();
//                int size =  Math.min(w, h);
//                setPreferredSize(new Dimension(size, size));
//                revalidate();
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Carte = new javax.swing.JPanel();
        ImageBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 350));
        setMinimumSize(new java.awt.Dimension(350, 350));
        setPreferredSize(new java.awt.Dimension(350, 350));
        setLayout(new java.awt.GridLayout(0, 1));

        Background.setBackground(new java.awt.Color(46, 52, 64));
        Background.setMaximumSize(new java.awt.Dimension(260, 130));
        Background.setMinimumSize(new java.awt.Dimension(260, 130));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(Background);

        Carte.setBackground(new java.awt.Color(255, 102, 51));
        Carte.setMaximumSize(new java.awt.Dimension(0, 0));
        Carte.setPreferredSize(new java.awt.Dimension(100, 100));

        ImageBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simudemie_logo_100px_63px.png"))); // NOI18N

        javax.swing.GroupLayout CarteLayout = new javax.swing.GroupLayout(Carte);
        Carte.setLayout(CarteLayout);
        CarteLayout.setHorizontalGroup(
            CarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CarteLayout.setVerticalGroup(
            CarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(Carte);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Carte;
    private javax.swing.JLabel ImageBackground;
    // End of variables declaration//GEN-END:variables
}
