/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.onglets;

import ca.ulaval.glo2004.afficheur.objetsScenario.ObjetScenarioMaladie;

/**
 *
 * @author Jonathan
 */
public class OngletScenarioMaladie extends OngletUI {
        
    public int getIndexCourant() {
        int index = -1;
        if(getCourant() != null) {
            ObjetScenarioMaladie osm = (ObjetScenarioMaladie) getCourant();
            index = osm.getIndex();
        }
        return index;
    }
    
    public void ajouterObjetUI(ObjetScenarioMaladie osm) {
        objets.add(osm);
        
        if (objets.size() == 1) {
            this.onClickObjetUI(osm);
        }
    }
    
    public void clear() {
        objets.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(46, 52, 64));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 35, 35));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void AddScenarioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddScenarioButtonMouseClicked
  
    }//GEN-LAST:event_AddScenarioButtonMouseClicked
                       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
