/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.onglets;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author Jonathan
 */
public class OngletTitre extends javax.swing.JPanel implements ActionListener {
    
    private final Timer timer;
    private float alphaImage = 0, alphaText = 0;
    private boolean alphaImageDone;
    
    private final int finalLogoYOffset = 100;
    
    private int centeredLogoX;
    private int centeredLogoY, logoY;
    private int initialY;
    private Image image, text;
    
    public OngletTitre() {
        initComponents();
        timer = new Timer(16, this);
        timer.start();
        
        try {
            text = ImageIO.read(getClass().getResource("/icons/simudemie_txt.png"));
            image = ImageIO.read(getClass().getResource("/icons/virus.png"));
        } catch (Exception e) {
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        alphaImageDone = alphaImage >= 0.99f;
        
        if (alphaImage < 0.99f) {
            alphaImage += 0.02f;
            
            initialY = centeredLogoY;
            logoY = initialY;
        }
        else if (initialY - finalLogoYOffset < logoY) {
            logoY -= 2;
        }
        else {
            if (alphaText < 0.99f) {
                alphaText += 0.02f;
            }
        }
        centeredLogoX = getBounds().width/2 - image.getWidth(null) / 2;
        repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        centeredLogoY = getBounds().height/2 - image.getHeight(null) / 2;
        centeredLogoX = getBounds().width/2 - image.getWidth(null) / 2;
        
        Graphics2D gr = (Graphics2D)g;
        gr.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, alphaImage));
        gr.drawImage(image, centeredLogoX, alphaImageDone ? logoY : centeredLogoY, null);
        
        if (alphaImageDone) {
            Graphics2D textGr = (Graphics2D)g;
            textGr.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, alphaText));
            textGr.drawImage(text, centeredLogoX - 125, logoY + image.getHeight(null), null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(46, 52, 64));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
