/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.onglets;

import ca.ulaval.glo2004.afficheur.objetsUI.ObjetUI;
import ca.ulaval.glo2004.domaine.controleur.GestionnaireCreation;
import java.util.ArrayList;

/**
 *
 * @author Jonathan
 */
public abstract class OngletUI extends javax.swing.JPanel {

    protected ArrayList<ObjetUI> objets = new ArrayList<>();
    protected ObjetUI courant;
    public GestionnaireCreation gestionnaireCreation; // TODO: Refactor pour utiliser un observer maybe ou un genre d'event listener avec les actions
    
    public OngletUI() {
        initComponents();
        gestionnaireCreation = new GestionnaireCreation();
    }
    
    public int getIndexCourant() {
        if (courant != null) {
            return objets.indexOf(courant);
        }
        return -1;
    }
    
    public ObjetUI getCourant() {
        return courant;
    }

    public void ajouterObjetUI() {
    }
    
    public void retirerCourant() {
        objets.remove(courant);
        if (!objets.isEmpty()) {
            onClickObjetUI(objets.get(0));
        }
    }
    
    public void onClickObjetUI(ObjetUI objet) {
        if (courant != null &&
            objet != courant) {
            courant.setToggled(false);
        }
        
        courant = objet;
        
        // Voir dans la liste et toggle le bon avec le bon index
        courant.setToggled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
