/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.CreationCarte;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Jonathan
 */
public class CreationCarte extends javax.swing.JPanel {
    
    private Mode mode;
    private int carteIndex;
    private CreationCarteToggle toggleCourant;
    
    public CreationCarte(int index) {
        initComponents();
        
        InformationsPanel.setBackground(new Color(59, 66, 82));
        
        BoutonSelection.init(this, new Selection(this), "icons8_cursor_25px");
        BoutonCrayon.init(this, new Creation(this), "icons8_pen_25px");
        BoutonRegion.init(this, new ca.ulaval.glo2004.afficheur.CreationCarte.Region(this), "icons8_scissors_25px");
        BoutonLien.init(this, new LienPays(this), "icons8_chain_25px");
        onToggleClick(BoutonSelection);
        
        carteIndex = index;
        CreationCartePanel.setCreationCarte(this);
    }
    
    public CreationCartePanel getPanel() {
        return CreationCartePanel;
    }
    
    public int getIndexCarte() {
        return carteIndex;
    }
    
    public Mode getMode() {
        return mode;
    }
    
    public JPanel getInformationsPanel() {
        return InformationsPanel;
    }
    
    public void onToggleClick(CreationCarteToggle bouton) {
        if (toggleCourant != null) {
            toggleCourant.setToggle(false);
        }
        
        if (mode != null) {
            mode.onDesactive();
        }
        
        mode = bouton.getMode();
        mode.onActive();
        
        toggleCourant = bouton;
        toggleCourant.setToggle(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LienButtonGroup = new javax.swing.ButtonGroup();
        CreationCartePanel = new ca.ulaval.glo2004.afficheur.CreationCarte.CreationCartePanel();
        InformationsPanel = new javax.swing.JPanel();
        ToolBar = new javax.swing.JPanel();
        BoutonSelection = new ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle();
        BoutonCrayon = new ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle();
        BoutonRegion = new ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle();
        BoutonLien = new ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle();

        setBackground(new java.awt.Color(46, 52, 64));
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout CreationCartePanelLayout = new javax.swing.GroupLayout(CreationCartePanel);
        CreationCartePanel.setLayout(CreationCartePanelLayout);
        CreationCartePanelLayout.setHorizontalGroup(
            CreationCartePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        CreationCartePanelLayout.setVerticalGroup(
            CreationCartePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        add(CreationCartePanel, java.awt.BorderLayout.CENTER);

        InformationsPanel.setFocusable(false);
        InformationsPanel.setPreferredSize(new java.awt.Dimension(225, 0));
        InformationsPanel.setLayout(new java.awt.BorderLayout());
        add(InformationsPanel, java.awt.BorderLayout.EAST);

        ToolBar.setBackground(new java.awt.Color(67, 76, 94));
        ToolBar.setPreferredSize(new java.awt.Dimension(968, 50));
        ToolBar.setLayout(new javax.swing.BoxLayout(ToolBar, javax.swing.BoxLayout.X_AXIS));
        ToolBar.add(BoutonSelection);
        ToolBar.add(BoutonCrayon);
        ToolBar.add(BoutonRegion);
        ToolBar.add(BoutonLien);

        add(ToolBar, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle BoutonCrayon;
    private ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle BoutonLien;
    private ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle BoutonRegion;
    private ca.ulaval.glo2004.afficheur.CreationCarte.CreationCarteToggle BoutonSelection;
    private ca.ulaval.glo2004.afficheur.CreationCarte.CreationCartePanel CreationCartePanel;
    private javax.swing.JPanel InformationsPanel;
    private javax.swing.ButtonGroup LienButtonGroup;
    private javax.swing.JPanel ToolBar;
    // End of variables declaration//GEN-END:variables
}
