/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.CreationCarte;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.domaine.Carte;
import ca.ulaval.glo2004.domaine.VoieLiaison;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Jonathan
 */
public class InformationsLienPanel extends javax.swing.JPanel implements ActionListener {
    
    private VoieLiaison lien;
    private final Carte carte;
    private JButton terrestre, maritime, aerien;
    
    public InformationsLienPanel(Carte carte) {
        this.carte = carte;
        initComponents();
        
        InformationsLienLabel.setFont(FontRegister.RobotoLight.deriveFont(17f));
        LienOrigineLabel.setFont(FontRegister.RobotoLight.deriveFont(15f));
        LienDestinationLabel.setFont(FontRegister.RobotoLight.deriveFont(15f));
    }
    
    public void setLien(VoieLiaison lien) {
        this.lien = lien;
        LienOrigineLabel.setText("Origine : " + lien.getPaysOrigine().getNom());
        LienDestinationLabel.setText("Dest. : " + lien.getPaysDestination().getNom());
        
        // Supprime tous anciens
        BoutonsLiens.removeAll();
        
        ArrayList<VoieLiaison.TypeVoie> nonUtilisees = carte.getVoiesDisponibles(lien.getPaysOrigine(), lien.getPaysDestination());
        for (VoieLiaison.TypeVoie voie : nonUtilisees) {
            ajouterBoutonRadio(voie);
        }
        
        BoutonsLiens.revalidate();
    }
    
    private void ajouterBoutonRadio(VoieLiaison.TypeVoie voie) {       
        switch (voie) {
            case Terrestre:
                terrestre = new JButton();
                terrestre.setText("Lien Terrestre");
                terrestre.addActionListener(this);
                terrestre.setFont(FontRegister.RobotoLight.deriveFont(13f));
                terrestre.setActionCommand("Terrestre");
                terrestre.setFocusable(false);
                BoutonsLiens.add(terrestre);
                break;
            case Maritime:
                maritime = new JButton();
                maritime.setText("Lien Maritime");
                maritime.addActionListener(this);
                maritime.setFont(FontRegister.RobotoLight.deriveFont(13f));
                maritime.setActionCommand("Maritime");
                maritime.setFocusable(false);
                BoutonsLiens.add(maritime);
                break;
            case Aerien:
                aerien = new JButton();
                aerien.setText("Lien Aerien");
                aerien.addActionListener(this);
                aerien.setFont(FontRegister.RobotoLight.deriveFont(13f));
                aerien.setActionCommand("Aerien");
                aerien.setFocusable(false);
                BoutonsLiens.add(aerien);
                break;
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        setVoie(VoieLiaison.TypeVoie.valueOf(e.getActionCommand()));
        setLien(lien);
        this.getRootPane().repaint();
    }
    
    private void setVoie(VoieLiaison.TypeVoie voie) {
        lien.setType(voie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LienLabels = new javax.swing.JPanel();
        InformationsLienLabel = new javax.swing.JLabel();
        LienOrigineLabel = new javax.swing.JLabel();
        LienDestinationLabel = new javax.swing.JLabel();
        BoutonsLiens = new javax.swing.JPanel();
        SupprimeBouton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 20));

        LienLabels.setOpaque(false);
        LienLabels.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        InformationsLienLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InformationsLienLabel.setText("Informations Lien");
        LienLabels.add(InformationsLienLabel);

        LienOrigineLabel.setText("Origine : ");
        LienLabels.add(LienOrigineLabel);

        LienDestinationLabel.setText("Dest. :");
        LienLabels.add(LienDestinationLabel);

        add(LienLabels, java.awt.BorderLayout.NORTH);

        BoutonsLiens.setFocusable(false);
        BoutonsLiens.setOpaque(false);
        BoutonsLiens.setLayout(new java.awt.GridLayout(3, 0, 0, 5));
        add(BoutonsLiens, java.awt.BorderLayout.CENTER);

        SupprimeBouton.setText("Retirer Lien");
        SupprimeBouton.setFocusable(false);
        SupprimeBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SupprimeBoutonMouseReleased(evt);
            }
        });
        add(SupprimeBouton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimeBoutonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimeBoutonMouseReleased
        //lien.getPaysOrigine().retirerVoie(lien);
        //lien.getPaysDestination().retirerVoie(lien);
    }//GEN-LAST:event_SupprimeBoutonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoutonsLiens;
    private javax.swing.JLabel InformationsLienLabel;
    private javax.swing.JLabel LienDestinationLabel;
    private javax.swing.JPanel LienLabels;
    private javax.swing.JLabel LienOrigineLabel;
    private javax.swing.JButton SupprimeBouton;
    // End of variables declaration//GEN-END:variables
}
