/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.Simulation.objetsUI;

import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.domaine.VoieLiaison;
import ca.ulaval.glo2004.domaine.VoieLiaison.TypeVoie;
import ca.ulaval.glo2004.domaine.controleur.GestionnaireScenario;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class ObjetSimulationVoieLiaison extends javax.swing.JPanel {
    
    private TypeVoie type;
    private boolean mouseOver, checked = true;
        
    public ObjetSimulationVoieLiaison() {
        initComponents();
        
        updateIcon();
    }
    
    public void setTypeVoie(TypeVoie type) {
        this.type = type;
        String texte = "Voie " + type;        
        if (type == TypeVoie.Aerien) {
            texte = "Voie Aérienne";
        }
        
        VoieLabel.setText(texte);
        VoieIcon1.setIcon(new ImageIcon(getClass().getResource("/icons/simulation/lien/" + type + ".png")));        
    }
    
    private void updateIcon() {
        String path = "/icons/simulation/mesure/";
        path += checked ? "checked" : "unchecked";
        path += mouseOver ? "_highlight.png" : ".png";
        Activer.setIcon(new ImageIcon(getClass().getResource(path)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Activer = new javax.swing.JLabel();
        VoieLabel = new javax.swing.JLabel();
        VoieIcon1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TransmissionLabel = new javax.swing.JLabel();
        Transmission = new javax.swing.JSpinner();

        setMinimumSize(new java.awt.Dimension(288, 60));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(288, 60));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new java.awt.GridLayout(2, 0, 0, -20));

        jPanel1.setMinimumSize(new java.awt.Dimension(141, 35));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        Activer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Activer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/simulation/mesure/unchecked.png"))); // NOI18N
        Activer.setMaximumSize(new java.awt.Dimension(50, 50));
        Activer.setMinimumSize(new java.awt.Dimension(50, 50));
        Activer.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(Activer);

        VoieLabel.setFont(FontRegister.RobotoLight.deriveFont(14f));
        VoieLabel.setText("Voie Terrestre");
        VoieLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        VoieLabel.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel1.add(VoieLabel);
        jPanel1.add(VoieIcon1);

        add(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 10));
        jPanel3.setMinimumSize(new java.awt.Dimension(288, 35));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(288, 35));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        TransmissionLabel.setFont(FontRegister.RobotoLight.deriveFont(14f));
        TransmissionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TransmissionLabel.setText("Probabilité de transmission :");
        TransmissionLabel.setAlignmentX(0.5F);
        TransmissionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TransmissionLabel.setMaximumSize(new java.awt.Dimension(200, 19));
        TransmissionLabel.setMinimumSize(new java.awt.Dimension(200, 19));
        TransmissionLabel.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(TransmissionLabel);

        Transmission.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 99.9d, 0.5d));
        jPanel3.add(Transmission);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseOver = true;
        updateIcon();
        this.getRootPane().repaint();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseOver = false;
        updateIcon();
        this.getRootPane().repaint();
    }//GEN-LAST:event_formMouseExited

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        checked = !checked; 
        updateIcon();
        this.getRootPane().repaint();
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Activer;
    private javax.swing.JSpinner Transmission;
    private javax.swing.JLabel TransmissionLabel;
    private javax.swing.JLabel VoieIcon1;
    private javax.swing.JLabel VoieLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
