/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.Simulation;

import ca.ulaval.glo2004.domaine.VoieLiaison;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class SimulationVoieLiaison extends javax.swing.JPanel {
    
    private boolean mouseOver, checked;
    
    public SimulationVoieLiaison() {
        initComponents();
    }
    
    public void setTypeVoie(VoieLiaison.TypeVoie type) {
        Label.setText("Voie " + type);
        Icon.setIcon(new ImageIcon(getClass().getResource("/icons/simulation/lien/" + type)));
    }
    
    private void updateIcon() {
        String path = "/icons/simulation/mesure/";
        path += checked ? "checked" : "unchecked";
        path += mouseOver ? "_highlight.png" : ".png";
        Checkbox.setIcon(new ImageIcon(getClass().getResource(path)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Checkbox = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        Checkbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Checkbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/simulation/mesure/unchecked.png"))); // NOI18N
        Checkbox.setMaximumSize(new java.awt.Dimension(50, 50));
        Checkbox.setMinimumSize(new java.awt.Dimension(50, 50));
        Checkbox.setPreferredSize(new java.awt.Dimension(50, 50));
        add(Checkbox);

        Label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label.setText("Voie Terrestre       ");
        Label.setPreferredSize(new java.awt.Dimension(50, 16));
        add(Label);

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/simulation/lien/terrestre.png"))); // NOI18N
        add(Icon);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseOver = true;
        updateIcon();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseOver = true;
        updateIcon();
    }//GEN-LAST:event_formMouseExited

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        checked = !checked;
        updateIcon();
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Checkbox;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Label;
    // End of variables declaration//GEN-END:variables
}
