/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.Simulation;

import ca.ulaval.glo2004.afficheur.BoutonToggle;
import ca.ulaval.glo2004.afficheur.PanelArrondi;
import java.awt.Color;

/**
 *
 * @author Jonathan
 */
public class SimulationTabs extends PanelArrondi {
    
    private BoutonToggle toggleCourant;
    private Simulation simulation;
    
    public SimulationTabs() {
        initComponents();
        
        try {
            Contenu.setBackground(new Color(76, 86, 106, 100));
            BoutonMesures.init(this, "icons8_wash_your_hands_30px");
        }
        catch(Exception e) {
        }
    }
    
    public void setSimulation(Simulation simulation) {
        this.simulation = simulation;
    }
    
    public void onToggleClick(BoutonToggle toggle) {
        Contenu.setVisible(toggle != null);
        
        if (toggleCourant != null) {
            toggleCourant.setToggle(false);
        }
        
        toggleCourant = toggle;
        
        if (toggleCourant != null) {
            toggleCourant.setToggle(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanelParent = new javax.swing.JPanel();
        SidePanel = new ca.ulaval.glo2004.afficheur.PanelArrondi();
        BoutonMesures = new ca.ulaval.glo2004.afficheur.BoutonToggle();
        Contenu = new ca.ulaval.glo2004.afficheur.PanelArrondi();

        setOpaque(false);
        setLayout(new javax.swing.OverlayLayout(this));

        SidePanelParent.setOpaque(false);
        SidePanelParent.setLayout(new java.awt.BorderLayout());

        SidePanel.setMaximumSize(new java.awt.Dimension(100, 200));
        SidePanel.setMinimumSize(new java.awt.Dimension(100, 200));
        SidePanel.setPreferredSize(new java.awt.Dimension(50, 200));
        SidePanel.setLayout(new java.awt.GridLayout(6, 1, 0, 10));
        SidePanel.add(BoutonMesures);

        SidePanelParent.add(SidePanel, java.awt.BorderLayout.WEST);

        add(SidePanelParent);

        javax.swing.GroupLayout ContenuLayout = new javax.swing.GroupLayout(Contenu);
        Contenu.setLayout(ContenuLayout);
        ContenuLayout.setHorizontalGroup(
            ContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        ContenuLayout.setVerticalGroup(
            ContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        add(Contenu);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.ulaval.glo2004.afficheur.BoutonToggle BoutonMesures;
    private ca.ulaval.glo2004.afficheur.PanelArrondi Contenu;
    private ca.ulaval.glo2004.afficheur.PanelArrondi SidePanel;
    private javax.swing.JPanel SidePanelParent;
    // End of variables declaration//GEN-END:variables
}
