/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ulaval.glo2004.afficheur.MenuPrincipal.panels;

import ca.ulaval.glo2004.afficheur.utilsUI.Couleurs;
import ca.ulaval.glo2004.afficheur.utilsUI.PanelArrondi;
import ca.ulaval.glo2004.afficheur.utilsUI.FontRegister;
import ca.ulaval.glo2004.domaine.Carte;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Jonathan
 */
public class ApercuPanel extends PanelArrondi {
    /**
     * Creates new form ScenarioMapPanel
     */
    public ApercuPanel() {
        initComponents();
        
        setBackground(Couleurs.pannelArrondi);
        try {
            NomCarteLabel.setFont(FontRegister.RobotoThin.deriveFont(21f));
            AideLabel.setFont(FontRegister.RobotoLight.deriveFont(14f));
        }
        catch(Exception e) {
        }
        
        // Pas besoin en mode creation carte
        ExportCarteBouton.setVisible(false);
        
        setPreviewVisibility(false);
    }
    
    public void setPreviewVisibility(boolean toggle) {
        ConteneurApercuCartePanel.setVisible(toggle);
    }
    
    public void setCarte(Carte carte) {
        ApercuCarte.setCarte(carte);
    }
    
    private void prendrePhoto() {
        BufferedImage img = new BufferedImage(ApercuCarte.getWidth(), ApercuCarte.getHeight(), BufferedImage.TYPE_INT_RGB);
        
        ApercuCarte.paint(img.getGraphics());
        
        try {
            ImageIO.write(img, "png", new File("saved.png"));
        }
        catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreApercuCartePanel = new javax.swing.JPanel();
        NomCarteLabel = new javax.swing.JLabel();
        ExportCarteBouton = new javax.swing.JLabel();
        ConteneurApercuCartePanel = new javax.swing.JPanel();
        AideParent = new javax.swing.JPanel();
        AidePanel = new ca.ulaval.glo2004.afficheur.utilsUI.PanelArrondi();
        AideLabel = new javax.swing.JLabel();
        ApercuCarte = new ca.ulaval.glo2004.afficheur.CreationCarte.panels.CarteApercu();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.BorderLayout());

        TitreApercuCartePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        TitreApercuCartePanel.setOpaque(false);
        TitreApercuCartePanel.setLayout(new java.awt.BorderLayout());

        NomCarteLabel.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        NomCarteLabel.setText("Aperçu");
        TitreApercuCartePanel.add(NomCarteLabel, java.awt.BorderLayout.CENTER);

        ExportCarteBouton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_unsplash_20px.png"))); // NOI18N
        ExportCarteBouton.setToolTipText("Exporter la carte en format PNG");
        ExportCarteBouton.setMaximumSize(new java.awt.Dimension(25, 25));
        ExportCarteBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExportCarteBoutonMouseReleased(evt);
            }
        });
        TitreApercuCartePanel.add(ExportCarteBouton, java.awt.BorderLayout.EAST);

        add(TitreApercuCartePanel, java.awt.BorderLayout.NORTH);

        ConteneurApercuCartePanel.setOpaque(false);
        ConteneurApercuCartePanel.setLayout(new javax.swing.OverlayLayout(ConteneurApercuCartePanel));

        AideParent.setOpaque(false);

        AidePanel.setLayout(new java.awt.BorderLayout());

        AideLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AideLabel.setText("Indice: utilisez la souris pour zoomer et se déplacer.");
        AideLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15));
        AidePanel.add(AideLabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout AideParentLayout = new javax.swing.GroupLayout(AideParent);
        AideParent.setLayout(AideParentLayout);
        AideParentLayout.setHorizontalGroup(
            AideParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AideParentLayout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(AidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        AideParentLayout.setVerticalGroup(
            AideParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AideParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        ConteneurApercuCartePanel.add(AideParent);

        javax.swing.GroupLayout ApercuCarteLayout = new javax.swing.GroupLayout(ApercuCarte);
        ApercuCarte.setLayout(ApercuCarteLayout);
        ApercuCarteLayout.setHorizontalGroup(
            ApercuCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        ApercuCarteLayout.setVerticalGroup(
            ApercuCarteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        ConteneurApercuCartePanel.add(ApercuCarte);

        add(ConteneurApercuCartePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ExportCarteBoutonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportCarteBoutonMouseReleased
        prendrePhoto();
    }//GEN-LAST:event_ExportCarteBoutonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AideLabel;
    private ca.ulaval.glo2004.afficheur.utilsUI.PanelArrondi AidePanel;
    private javax.swing.JPanel AideParent;
    private ca.ulaval.glo2004.afficheur.CreationCarte.panels.CarteApercu ApercuCarte;
    private javax.swing.JPanel ConteneurApercuCartePanel;
    private javax.swing.JLabel ExportCarteBouton;
    private javax.swing.JLabel NomCarteLabel;
    private javax.swing.JPanel TitreApercuCartePanel;
    // End of variables declaration//GEN-END:variables
}
